services:
  - type: web
    name: data-analyst-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
